apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-template-app
  namespace: argocd
spec:
  project: default
  source:
    chart: helm-template
    repoURL: oci://docker.io/blgianini
    targetRevision: 0.0.1
    helm:
      values: |
        # Se você quiser sobrescrever valores do Chart
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true