replicaCount: 1

image:
  repository: meu-repo/minha-imagem
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
