name: Deploy usando Workflow Reutilizável

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: homelab-blgianini/reusable-workflows/.github/workflows/reusable-deploy.yaml@main
    with:
      name: ${{ github.event.repository.name }}